/* JARVIS V4.0.0 — finished-app visual system. */
export function installJarvisV4Ui(Panel){
 if(!Panel||Panel.prototype.__jarvisV4UiInstalled)return;
 const PREF_KEY='jarvis_v4_layout_preferences';
 const getPref=()=>{try{return JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch(_){return {}}};
 const savePref=p=>{try{localStorage.setItem(PREF_KEY,JSON.stringify(p))}catch(_){}};
 const stateMeta=core=>core?.classList.contains('state-think')?['think','#ffb000','rgba(255,176,0,.38)']:core?.classList.contains('state-listen')?['listen','#39ff88','rgba(57,255,136,.34)']:core?.classList.contains('state-speak')?['speak','#b56cff','rgba(181,108,255,.36)']:core?.classList.contains('state-search')?['search','#00eaff','rgba(0,234,255,.36)']:['ready','#00eaff','rgba(0,234,255,.28)'];
 Panel.prototype._v4InstallShell=function(){
   const r=this.shadowRoot;if(!r)return;
   if(!r.getElementById('jarvisV4ShellStyle')){const s=document.createElement('style');s.id='jarvisV4ShellStyle';s.textContent=`
    :host{--v4-bg:#020711;--v4-panel:#04121ddd;--v4-line:#00eaff24;--v4-text:#dffaff;--v4-muted:#7ca9b8}
    .tools{gap:8px!important}.tools button{border-radius:12px!important;background:#03101ce8!important;border:1px solid #00eaff35!important;box-shadow:0 10px 30px #0007!important}
    .panel{width:min(440px,calc(100vw - 24px))!important;padding:16px!important;border-radius:18px!important;background:linear-gradient(180deg,#051927f8,#020a12fc)!important;border:1px solid #00eaff2b!important;box-shadow:0 24px 80px #000b,0 0 0 1px #00eaff08 inset!important}
    .panel>.title{font-size:13px!important;letter-spacing:2.5px!important;color:#e8fbff!important;margin:0 0 5px!important}.panel>.note{font-size:9px!important;color:var(--v4-muted)!important;line-height:1.5!important;margin-bottom:14px!important}
    .section{margin-top:11px!important;padding:12px!important;border:1px solid var(--v4-line)!important;border-radius:13px!important;background:#03111ca6!important}.section>.title{border:0!important;margin:0 0 9px!important;padding:0 0 8px!important;border-bottom:1px solid #00eaff12!important;color:#93eaff!important;font-size:9px!important;letter-spacing:1.8px!important}
    .row,.system-tool{min-height:42px!important;padding:6px 0!important;border-bottom:1px solid #00eaff0d!important}.row button,.actions button,.dock-toggle{border-radius:9px!important;background:#062033cc!important;border:1px solid #00dfff2f!important}.row button:active,.actions button:active,.dock-toggle:active{background:#08314dcc!important}
    .actions{position:sticky!important;bottom:-16px!important;padding:14px 0 0!important;margin-top:12px!important;background:linear-gradient(180deg,transparent,#020a12 34%)!important}.actions button{min-height:42px!important;font-weight:700!important;letter-spacing:1px!important}
    details.jarvis-settings-details{margin:8px 0!important;border:1px solid #00eaff20!important;border-radius:11px!important;background:#020c15b8!important;overflow:hidden!important}details.jarvis-settings-details>summary{min-height:43px!important;padding:0 11px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:10px!important;list-style:none!important;color:#c6f5ff!important}details.jarvis-settings-details>summary::-webkit-details-marker{display:none!important}.jarvis-settings-body{padding:11px!important;border-top:1px solid #00eaff12!important}
    .v4-display-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;min-height:44px;padding:6px 0;border-bottom:1px solid #00eaff0d;font-size:9px}.v4-display-row select{min-width:138px;height:34px;border-radius:9px;background:#041522;color:#dffaff;border:1px solid #00eaff30;padding:0 8px}.v4-display-row small{display:block;color:#6f9baa;margin-top:3px;font-size:8px}
   `;r.appendChild(s)}
   const settings=r.getElementById('settingsPanel');if(!settings||settings.querySelector('.v4-layout-section'))return;
   const sec=document.createElement('div');sec.className='section v4-layout-section';sec.innerHTML='<div class="title">AFFICHAGE / POSITION</div><div class="note">Chaque bloc peut rester fixé sous le cœur, rester disponible uniquement dans le menu, ou être masqué.</div><div class="v4-display-options"></div>';
   const actions=settings.querySelector('.actions');settings.insertBefore(sec,actions);
   this._v4RenderDisplayOptions?.();
 };
 Panel.prototype._v4RenderDisplayOptions=function(){
   const box=this.shadowRoot?.querySelector('.v4-display-options');if(!box)return;
   const p=getPref(),labels={energy:['⚡ Énergie solaire','Production, consommation, import et export'],voice:['🎙️ Commandes JARVIS','Écoute, mute, test voix et saisie'],pipeline:['🧠 Assistant / Pipeline','Pipeline actif et routage'],led:['💡 Affichage & audio','Luminosité et volume'],log:['🖥️ Console','Journal technique JARVIS']};
   p.display=p.display||{energy:'dock',voice:'dock',pipeline:'menu',led:'menu',log:'menu'};box.innerHTML='';
   Object.entries(labels).forEach(([k,[name,desc]])=>{const row=document.createElement('div');row.className='v4-display-row';row.innerHTML=`<div><b>${name}</b><small>${desc}</small></div><select><option value="dock">SOUS LE CŒUR</option><option value="menu">MENU SEULEMENT</option><option value="hidden">MASQUÉ</option></select>`;const sel=row.querySelector('select');sel.value=p.display[k]||'menu';sel.onchange=()=>{p.display[k]=sel.value;savePref(p);this._v4ApplyDisplay?.()};box.appendChild(row)});
 };
 Panel.prototype._v4ApplyDisplay=function(){
   const p=getPref();p.display=p.display||{};const map=this._cardMap?.()||{};
   Object.entries(map).forEach(([k,card])=>{if(!card)return;const mode=p.display[k]||(k==='energy'||k==='voice'?'dock':'menu');card.dataset.v4Display=mode;card.style.display=mode==='dock'?'':'none'});
 };
 Panel.prototype._v4InstallCore=function(){
   const root=this._core?.shadowRoot,core=root?.getElementById('core');if(!root||!core)return;
   if(!root.getElementById('jarvisV4CoreStyle')){const s=document.createElement('style');s.id='jarvisV4CoreStyle';s.textContent=`
    :host{--jv-core-state:#00eaff;--jv-core-state-soft:rgba(0,234,255,.28)}
    .core{isolation:isolate!important;overflow:visible!important}
    .v4-field,.v4-frame,.v4-segments,.v4-scan,.v4-pulse{position:absolute;pointer-events:none;border-radius:50%}
    .v4-field{inset:-11%;z-index:-3;background:radial-gradient(circle,transparent 52%,color-mix(in srgb,var(--jv-core-state) 8%,transparent) 67%,transparent 73%);filter:blur(3px);animation:v4Field 5s ease-in-out infinite}
    .v4-frame{inset:-6.2%;z-index:-1;border:1.5px solid var(--jv-core-state);box-shadow:0 0 13px var(--jv-core-state-soft),inset 0 0 10px color-mix(in srgb,var(--jv-core-state) 9%,transparent);opacity:.82;transition:.22s}
    .v4-segments{inset:-3%;z-index:-1;background:repeating-conic-gradient(from -90deg,color-mix(in srgb,var(--jv-core-state) 58%,transparent) 0 .8deg,transparent .8deg 5.5deg);-webkit-mask:radial-gradient(circle,transparent 91%,#000 92% 95%,transparent 96%);mask:radial-gradient(circle,transparent 91%,#000 92% 95%,transparent 96%);opacity:.52;animation:v4Spin 24s linear infinite}
    .v4-scan{inset:8%;z-index:2;border:1px solid color-mix(in srgb,var(--jv-core-state) 55%,transparent);box-shadow:0 0 18px var(--jv-core-state-soft),inset 0 0 18px var(--jv-core-state-soft);opacity:0}
    .v4-pulse{inset:31%;z-index:4;background:radial-gradient(circle,#fff 0 3%,var(--jv-core-state) 7%,color-mix(in srgb,var(--jv-core-state) 24%,transparent) 37%,transparent 72%);filter:drop-shadow(0 0 15px var(--jv-core-state));opacity:.55;animation:v4IdlePulse 3.4s ease-in-out infinite}
    #stateDock{display:flex!important;width:100%!important;justify-content:center!important;align-items:center!important;text-align:center!important;box-sizing:border-box!important;margin:-4px auto 12px!important}
    #stateDock .label{position:static!important;left:auto!important;right:auto!important;bottom:auto!important;transform:none!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;width:auto!important;max-width:calc(100vw - 42px)!important;margin:0 auto!important;padding:5px 13px!important;min-height:27px!important;border-radius:999px!important;background:#020711d9!important;border:1px solid currentColor!important;color:var(--jv-core-state)!important;text-align:center!important;box-shadow:0 0 12px var(--jv-core-state-soft)!important}
    .core.state-think .v4-frame{opacity:1;box-shadow:0 0 22px rgba(255,176,0,.52),inset 0 0 15px rgba(255,176,0,.13);animation:v4ThinkFrame .9s ease-in-out infinite}.core.state-think .v4-segments{opacity:.95;animation-duration:4.2s}.core.state-think .v4-pulse{animation:v4ThinkPulse .72s ease-in-out infinite;opacity:.95}.core.state-listen .v4-frame{opacity:.95}.core.state-listen .v4-pulse{animation-duration:1.8s}.core.state-speak .v4-pulse{animation:v4SpeakPulse .58s ease-in-out infinite}.core.state-search .v4-segments{animation-duration:7s;animation-direction:reverse}
    .core.v4-boot .ring{opacity:0!important;transform:scale(.18)!important}.core.v4-boot .r5{animation:v4BuildRing .5s .22s forwards!important}.core.v4-boot .r4{animation:v4BuildRing .56s .42s forwards!important}.core.v4-boot .r3{animation:v4BuildRing .62s .62s forwards!important}.core.v4-boot .r2{animation:v4BuildRing .68s .82s forwards!important}.core.v4-boot .r1{animation:v4BuildRing .74s 1.02s forwards!important}
    .core.v4-boot .glow{opacity:0!important;animation:v4Ignite .75s .05s forwards!important}.core.v4-boot .leds{opacity:0!important;animation:v4Reveal .65s 1.2s forwards!important}.core.v4-boot .v4-segments{opacity:0!important;animation:v4BuildSegments .75s 1.42s forwards!important}.core.v4-boot .v4-frame{opacity:0!important;animation:v4CloseFrame .9s 1.72s forwards!important}.core.v4-boot .v4-scan{animation:v4Scan 2.35s .18s forwards!important}.core.v4-boot .v4-pulse{opacity:0!important;animation:v4IgnitePulse 1s .28s forwards!important}.core.v4-boot .soul{opacity:1!important;animation:v4SoulBirth 1.55s .5s both!important}
    @keyframes v4Field{0%,100%{transform:scale(.985);opacity:.36}50%{transform:scale(1.025);opacity:.68}}@keyframes v4Spin{to{transform:rotate(360deg)}}@keyframes v4IdlePulse{0%,100%{transform:scale(.94);opacity:.38}50%{transform:scale(1.08);opacity:.72}}@keyframes v4ThinkFrame{0%,100%{transform:scale(.995)}50%{transform:scale(1.012)}}@keyframes v4ThinkPulse{0%,100%{transform:scale(.9)}50%{transform:scale(1.18)}}@keyframes v4SpeakPulse{0%,100%{transform:scale(.9);opacity:.5}50%{transform:scale(1.22);opacity:1}}@keyframes v4BuildRing{0%{opacity:0;transform:scale(.18) rotate(-55deg)}75%{opacity:1}100%{opacity:1;transform:scale(1) rotate(0)}}@keyframes v4Ignite{0%{opacity:0;transform:scale(.05)}55%{opacity:1;transform:scale(1.25)}100%{opacity:1;transform:scale(1)}}@keyframes v4Reveal{from{opacity:0;filter:blur(6px)}to{opacity:1;filter:none}}@keyframes v4BuildSegments{0%{opacity:0;transform:scale(.65) rotate(-70deg)}100%{opacity:.52;transform:scale(1) rotate(0)}}@keyframes v4CloseFrame{0%{opacity:0;transform:scale(.72);clip-path:polygon(50% 50%,50% 0,50% 0)}70%{opacity:1}100%{opacity:.82;transform:scale(1);clip-path:circle(60% at 50% 50%)}}@keyframes v4Scan{0%{opacity:0;transform:scale(.08)}32%{opacity:1}78%{opacity:.45;transform:scale(1.18)}100%{opacity:0;transform:scale(1.35)}}@keyframes v4IgnitePulse{0%{opacity:0;transform:scale(.05)}60%{opacity:1;transform:scale(1.4)}100%{opacity:.55;transform:scale(1)}}@keyframes v4SoulBirth{0%{opacity:0;filter:blur(8px);transform:scale(.4)}55%{opacity:1;filter:blur(1px);transform:scale(1.12)}100%{opacity:var(--soul-end,0);filter:none;transform:scale(1)}}
   `;root.appendChild(s)}
   if(!core.querySelector('.v4-field')){['v4-field','v4-frame','v4-segments','v4-scan','v4-pulse'].forEach(c=>{const e=document.createElement('div');e.className=c;core.prepend(e)})}
   const sync=()=>{const [k,c,soft]=stateMeta(core);core.style.setProperty('--jv-core-state',c);core.style.setProperty('--jv-core-state-soft',soft);const dock=root.getElementById('stateDock');if(dock)dock.dataset.state=k};sync();
   if(!core.__v4Observer){const o=new MutationObserver(sync);o.observe(core,{attributes:true,attributeFilter:['class']});core.__v4Observer=o}
   if(!core.dataset.v4BootPlayed){core.dataset.v4BootPlayed='1';core.classList.add('v4-boot');setTimeout(()=>{core.classList.remove('v4-boot');sync()},2850)}
 };
 const wrap=(name,after)=>{const base=Panel.prototype[name];if(!base)return;Panel.prototype[name]=function(...a){const out=base.apply(this,a);if(out&&typeof out.then==='function')return out.then(v=>{after.call(this);return v});after.call(this);return out}};
 wrap('_render',function(){this._v4InstallShell()});wrap('_renderCards',function(){this._v4InstallShell();this._v4RenderDisplayOptions();this._v4ApplyDisplay()});wrap('_applySystemDock',function(){this._v4ApplyDisplay()});wrap('_bootCore',function(){this._v4InstallShell();this._v4InstallCore();this._v4ApplyDisplay();requestAnimationFrame(()=>this._v4InstallCore())});
 Panel.prototype.__jarvisV4UiInstalled=true;
}
