/* JARVIS V4.0.0 — unified premium visual system + security selection. */
export function installJarvisV4Ui(Panel){
 if(!Panel||Panel.prototype.__jarvisV4UiInstalled)return;
 const stateMeta=core=>core?.classList.contains('state-think')?['think','#ffb000','rgba(255,176,0,.38)']:core?.classList.contains('state-listen')?['listen','#39ff88','rgba(57,255,136,.34)']:core?.classList.contains('state-speak')?['speak','#b56cff','rgba(181,108,255,.36)']:core?.classList.contains('state-search')?['search','#00eaff','rgba(0,234,255,.36)']:['ready','#00eaff','rgba(0,234,255,.28)'];
 Panel.prototype._v4InstallShell=function(){
  const r=this.shadowRoot;if(!r)return;
  if(!r.getElementById('jarvisV4UnifiedStyle')){const s=document.createElement('style');s.id='jarvisV4UnifiedStyle';s.textContent=`
  :host{--v4-line:#00eaff1c;--v4-line-strong:#00eaff42;--v4-muted:#6f97a6;--v4-panel:#06111adf;--v4-card:#081924b8;color:#dffaff}
  .tools{gap:10px!important;top:14px!important;right:14px!important}.tools button{width:42px!important;height:42px!important;border-radius:14px!important;background:linear-gradient(180deg,#071a27f0,#03101be8)!important;border:1px solid #00eaff30!important;box-shadow:0 10px 30px #0008,inset 0 1px 0 #ffffff09!important;color:#dffaff!important;font-size:17px!important;backdrop-filter:blur(14px)!important}.tools button:hover{border-color:#00eaff66!important;box-shadow:0 12px 36px #0009,0 0 22px #00eaff12!important}
  .version{right:16px!important;bottom:10px!important;padding:4px 8px!important;border-radius:8px!important;background:#020811aa!important;border:1px solid #00eaff10!important;color:#658a98!important;letter-spacing:1.2px!important}
  .panel{top:12px!important;right:12px!important;width:min(500px,calc(100vw - 24px))!important;max-height:calc(100vh - 24px)!important;padding:18px 18px 20px!important;border-radius:24px!important;background:linear-gradient(180deg,rgba(8,24,35,.985),rgba(3,10,16,.99))!important;border:1px solid #00eaff24!important;box-shadow:0 30px 90px #000d,inset 0 1px 0 #ffffff08!important;backdrop-filter:blur(26px)!important}
  .panel::before{content:'';position:sticky;display:block;top:-18px;height:4px;margin:-18px -18px 14px;background:linear-gradient(90deg,transparent,#00eaff66 24%,#00eaffcc 50%,#00eaff66 76%,transparent);box-shadow:0 0 24px #00eaff20;z-index:4}
  .panel>.title{font-size:15px!important;letter-spacing:3px!important;color:#effcff!important;margin:0 0 6px!important;text-shadow:0 0 16px #00eaff18!important}.panel>.note{font-size:9px!important;color:#789cab!important;line-height:1.55!important;margin-bottom:14px!important}
  .section{margin-top:12px!important;padding:13px!important;border:1px solid var(--v4-line)!important;border-radius:16px!important;background:linear-gradient(180deg,#071722b8,#041019b0)!important;box-shadow:inset 0 1px 0 #ffffff05!important}.section:hover{border-color:#00eaff2f!important}.section>.title{display:flex!important;align-items:center!important;gap:7px!important;padding:0 0 9px!important;margin:0 0 8px!important;border-bottom:1px solid #00eaff10!important;color:#9defff!important;font-size:10px!important;letter-spacing:1.8px!important}.section>.note{color:#668b99!important;font-size:8px!important;line-height:1.5!important}
  .setting{min-height:52px!important;padding:5px 0!important;border-bottom:1px solid #00eaff0a!important}.setting:last-child{border-bottom:0!important}.setting b{font-size:10px!important;font-weight:700!important;color:#e7fbff!important}.setting small{color:#648692!important;font-size:8px!important}.setting select{min-width:154px!important;height:36px!important;padding:0 10px!important;border-radius:11px!important;background:#04131e!important;border:1px solid #00eaff25!important;color:#dffaff!important}.setting select:focus{border-color:#00eaff66!important;outline:none!important;box-shadow:0 0 0 2px #00eaff0c!important}
  .order button,.actions button,.memrow button,.v4-security-save{border-radius:11px!important;background:linear-gradient(180deg,#092133,#061725)!important;border:1px solid #00eaff28!important;color:#dffaff!important;box-shadow:inset 0 1px 0 #ffffff05!important}.order button:hover,.actions button:hover,.memrow button:hover,.v4-security-save:hover{border-color:#00eaff55!important;background:#0a263a!important}
  .actions{position:sticky!important;bottom:-20px!important;padding:16px 0 2px!important;background:linear-gradient(180deg,transparent,#030a10 38%)!important;z-index:5!important}.actions button{min-height:40px!important;font-weight:700!important;letter-spacing:.8px!important}.actions button:last-child{border-color:#39ff8850!important;color:#9bffc4!important}
  .memrow input,.v4-security-search input{box-sizing:border-box;height:40px!important;padding:0 11px!important;border:1px solid #00eaff28!important;border-radius:11px!important;background:#020c13!important;color:#dffaff!important;outline:none!important}.memrow input:focus,.v4-security-search input:focus{border-color:#00eaff66!important;box-shadow:0 0 0 2px #00eaff0b!important}
  .v4-security-list{max-height:300px;overflow:auto;border:1px solid #00eaff12;border-radius:12px;background:#020b1280}.v4-security-row{display:grid;grid-template-columns:26px 1fr auto;gap:8px;align-items:center;min-height:46px;padding:7px 9px;border-bottom:1px solid #00eaff09;font-size:9px}.v4-security-row:hover{background:#00eaff05}.v4-security-row input{width:17px;height:17px;accent-color:#00eaff}.v4-security-row b{display:block}.v4-security-row small{display:block;opacity:.5;font:8px monospace}.v4-security-state,.v4-security-summary{font:8px monospace;opacity:.62}.v4-security-summary{padding-top:8px}.v4-security-save{width:100%;min-height:40px;margin-top:10px;font-weight:700}
  @media(max-width:650px){.panel{top:8px!important;right:8px!important;width:calc(100vw - 16px)!important;max-height:calc(100vh - 16px)!important;padding:15px!important;border-radius:20px!important}.tools{top:10px!important;right:10px!important}.tools button{width:40px!important;height:40px!important}.setting{grid-template-columns:1fr!important;gap:6px!important}.setting select{width:100%!important;min-width:0!important}.order{justify-content:flex-end}.section{padding:12px!important}}
  `;r.appendChild(s)}
  const settings=r.getElementById('settingsPanel');if(!settings||settings.querySelector('.v4-security-section'))return;
  const sec=document.createElement('div');sec.className='section v4-security-section';sec.innerHTML='<div class="title">🛡️ SÉCURITÉ · CAPTEURS SURVEILLÉS</div><div class="note">Le score Sécurité ne tient compte que des entités cochées ici.</div><div class="v4-security-search"><input id="v4SecuritySearch" placeholder="Rechercher caméra, porte, alarme, capteur…"></div><div class="v4-security-list" id="v4SecurityList">Chargement…</div><div class="v4-security-summary" id="v4SecuritySummary"></div><button class="v4-security-save" id="v4SecuritySave">ENREGISTRER LA SÉLECTION</button>';
  settings.insertBefore(sec,settings.querySelector('.actions'));sec.querySelector('#v4SecuritySearch').oninput=e=>this._v4RenderSecurityEntities(e.target.value);sec.querySelector('#v4SecuritySave').onclick=()=>this._v4SaveSecurityEntities()
 };
 Panel.prototype._v4LoadSecurityEntities=async function(){this._v4InstallShell();try{const d=await this._hass.callApi('GET','jarvis/settings');this._v4SecuritySelected=new Set(d?.settings?.security_entities||[])}catch(_){this._v4SecuritySelected=new Set()}this._v4RenderSecurityEntities('')};
 Panel.prototype._v4Candidates=function(){const domains=new Set(['binary_sensor','camera','alarm_control_panel','lock','cover']);return Object.values(this._hass?.states||{}).filter(s=>domains.has(String(s.entity_id||'').split('.')[0])).sort((a,b)=>String(a.attributes?.friendly_name||a.entity_id).localeCompare(String(b.attributes?.friendly_name||b.entity_id),'fr'))};
 Panel.prototype._v4RenderSecurityEntities=function(query=''){const box=this.shadowRoot?.getElementById('v4SecurityList'),summary=this.shadowRoot?.getElementById('v4SecuritySummary');if(!box)return;if(!this._v4SecuritySelected)this._v4SecuritySelected=new Set();const q=String(query).trim().toLowerCase(),list=this._v4Candidates().filter(s=>!q||s.entity_id.toLowerCase().includes(q)||String(s.attributes?.friendly_name||'').toLowerCase().includes(q));box.innerHTML='';list.slice(0,180).forEach(s=>{const id=s.entity_id,row=document.createElement('label');row.className='v4-security-row';row.innerHTML=`<input type="checkbox" ${this._v4SecuritySelected.has(id)?'checked':''}><div><b>${s.attributes?.friendly_name||id}</b><small>${id}</small></div><span class="v4-security-state">${s.state}</span>`;row.querySelector('input').onchange=e=>{e.target.checked?this._v4SecuritySelected.add(id):this._v4SecuritySelected.delete(id);summary.textContent=`${this._v4SecuritySelected.size} entité(s) sélectionnée(s)`};box.appendChild(row)});if(!list.length)box.textContent='Aucune entité trouvée.';if(summary)summary.textContent=`${this._v4SecuritySelected.size} entité(s) sélectionnée(s)`};
 Panel.prototype._v4SaveSecurityEntities=async function(){const ids=[...(this._v4SecuritySelected||new Set())],summary=this.shadowRoot?.getElementById('v4SecuritySummary');try{await this._hass.callApi('POST','jarvis/settings',{section:'security_entities',value:ids});if(summary)summary.textContent=`✓ ${ids.length} entité(s) enregistrée(s)`;this._jarvisLoadHealth?.()}catch(e){if(summary)summary.textContent='Erreur : '+e.message}};
 Panel.prototype._v4InstallCore=function(){
  const root=this._core?.shadowRoot,core=root?.getElementById('core');if(!root||!core)return;
  if(!root.getElementById('jarvisV4CoreStyle')){const s=document.createElement('style');s.id='jarvisV4CoreStyle';s.textContent=`
  :host{--jv-core-state:#00eaff;--jv-core-state-soft:rgba(0,234,255,.28)}
  .core{isolation:isolate!important;overflow:visible!important;width:min(74vw,420px)!important;height:min(74vw,420px)!important;margin:18px auto 48px!important;filter:drop-shadow(0 20px 42px #0008)}
  .v4-field,.v4-frame,.v4-halo,.v4-scan,.v4-pulse,.v4-reactor{position:absolute;pointer-events:none;border-radius:50%}.v4-field{inset:-13%;z-index:-4;background:radial-gradient(circle,transparent 48%,color-mix(in srgb,var(--jv-core-state) 8%,transparent) 63%,transparent 72%);filter:blur(8px);animation:v4Field 5s ease-in-out infinite}.v4-halo{inset:-6.5%;z-index:-2;border:1px solid color-mix(in srgb,var(--jv-core-state) 18%,transparent);box-shadow:0 0 34px color-mix(in srgb,var(--jv-core-state) 16%,transparent),inset 0 0 28px color-mix(in srgb,var(--jv-core-state) 7%,transparent);opacity:.82}.v4-frame{inset:-2.8%;z-index:-1;border:1px solid color-mix(in srgb,var(--jv-core-state) 72%,transparent);box-shadow:0 0 16px var(--jv-core-state-soft),inset 0 0 12px color-mix(in srgb,var(--jv-core-state) 9%,transparent);opacity:.92}.v4-scan{inset:11%;z-index:2;border:1px solid color-mix(in srgb,var(--jv-core-state) 42%,transparent);opacity:.34;animation:v4Scan 7s linear infinite}.v4-pulse{inset:27%;z-index:4;background:radial-gradient(circle,#fff 0 2%,var(--jv-core-state) 6%,color-mix(in srgb,var(--jv-core-state) 34%,transparent) 30%,transparent 69%);filter:drop-shadow(0 0 16px var(--jv-core-state));opacity:.68;animation:v4IdlePulse 3.2s ease-in-out infinite}.v4-reactor{inset:36%;z-index:5;border:1px solid color-mix(in srgb,var(--jv-core-state) 58%,transparent);box-shadow:inset 0 0 18px color-mix(in srgb,var(--jv-core-state) 20%,transparent),0 0 18px color-mix(in srgb,var(--jv-core-state) 16%,transparent);animation:v4Reactor 4.6s ease-in-out infinite}
  .glow{width:23%!important;height:23%!important;background:radial-gradient(circle,#fff 0 5%,#dfffff 7%,var(--jv-core-state) 17%,color-mix(in srgb,var(--jv-core-state) 48%,transparent) 38%,transparent 72%)!important;box-shadow:0 0 18px #fff8,0 0 34px var(--jv-core-state),0 0 82px var(--jv-core-state-soft)!important;animation:v4CoreBreath 2.7s ease-in-out infinite!important}.glow::before,.glow::after{content:'';position:absolute;border-radius:50%;pointer-events:none}.glow::before{inset:-24%;border:1px solid color-mix(in srgb,var(--jv-core-state) 52%,transparent);box-shadow:inset 0 0 12px color-mix(in srgb,var(--jv-core-state) 16%,transparent)}.glow::after{inset:-48%;border:1px solid color-mix(in srgb,var(--jv-core-state) 18%,transparent)}
  .ring{border-color:color-mix(in srgb,var(--jv-core-state) 34%,transparent)!important;box-shadow:none!important}.r1{opacity:.78!important;border-width:1px!important}.r2{opacity:.22!important}.r3{opacity:.48!important}.r4{opacity:.24!important}.r5{opacity:.32!important}.orbit{opacity:.34!important;border-color:color-mix(in srgb,var(--jv-core-state) 30%,transparent)!important}.satellite{background:var(--jv-core-state)!important;box-shadow:0 0 8px var(--jv-core-state),0 0 18px var(--jv-core-state-soft)!important}
  .leds{opacity:.92}.led{background:var(--jv-core-state)!important;box-shadow:0 0 6px var(--jv-core-state)!important}
  .label{left:50%!important;right:auto!important;bottom:-11%!important;transform:translateX(-50%)!important;width:max-content!important;max-width:calc(100vw - 42px)!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:6px 15px!important;border-radius:999px!important;background:linear-gradient(180deg,#06131de8,#02070ce8)!important;border:1px solid color-mix(in srgb,var(--jv-core-state) 48%,transparent)!important;color:var(--jv-core-state)!important;white-space:nowrap!important;box-shadow:0 10px 26px #0008,0 0 16px var(--jv-core-state-soft)!important;backdrop-filter:blur(10px)!important;font-size:11px!important;letter-spacing:3.5px!important}
  .core.state-think .v4-frame,.core.state-think .v4-reactor{box-shadow:0 0 24px rgba(255,176,0,.34),inset 0 0 20px rgba(255,176,0,.14)}.core.state-think .v4-pulse{animation-duration:1.3s}.core.state-listen .v4-pulse{animation-duration:1.7s}.core.state-speak .v4-pulse{animation-duration:.58s}.core.state-speak .v4-reactor{animation-duration:1s}
  .grid{gap:14px!important;max-width:980px!important}.card{border-radius:16px!important;border:1px solid #00eaff1d!important;background:linear-gradient(180deg,#061825d9,#030d15ed)!important;box-shadow:0 16px 38px #0005,inset 0 1px 0 #ffffff05!important}.card .title{letter-spacing:1.7px!important}
  .core.v4-boot .ring,.core.v4-boot .v4-halo,.core.v4-boot .v4-frame,.core.v4-boot .v4-reactor{opacity:0!important;transform:scale(.2)!important}.core.v4-boot .r5{animation:v4BuildRing .48s .18s forwards!important}.core.v4-boot .r4{animation:v4BuildRing .52s .34s forwards!important}.core.v4-boot .r3{animation:v4BuildRing .56s .5s forwards!important}.core.v4-boot .r2{animation:v4BuildRing .62s .66s forwards!important}.core.v4-boot .r1{animation:v4BuildRing .68s .82s forwards!important}.core.v4-boot .glow{opacity:0!important;animation:v4Ignite .72s .05s forwards!important}.core.v4-boot .v4-halo{animation:v4Close .72s 1.14s forwards!important}.core.v4-boot .v4-frame{animation:v4Close .82s 1.36s forwards!important}.core.v4-boot .v4-reactor{animation:v4Close .72s 1.58s forwards!important}
  @media(max-width:650px){.core{width:72vw!important;height:72vw!important;max-width:370px!important;max-height:370px!important;margin-top:14px!important}.label{bottom:-12%!important;font-size:10px!important;letter-spacing:3px!important}}
  @keyframes v4Field{50%{transform:scale(1.035);opacity:.72}}@keyframes v4IdlePulse{50%{transform:scale(1.09);opacity:.82}}@keyframes v4Scan{to{transform:rotate(360deg)}}@keyframes v4Reactor{0%,100%{transform:scale(.96);opacity:.58}50%{transform:scale(1.05);opacity:.95}}@keyframes v4CoreBreath{0%,100%{transform:scale(.96);opacity:.88}50%{transform:scale(1.08);opacity:1}}@keyframes v4BuildRing{0%{opacity:0;transform:scale(.2) rotate(-36deg)}100%{opacity:1;transform:scale(1) rotate(0)}}@keyframes v4Ignite{0%{opacity:0;transform:scale(.04)}55%{opacity:1;transform:scale(1.18)}100%{opacity:1;transform:scale(1)}}@keyframes v4Close{from{opacity:0;transform:scale(.74)}to{opacity:.9;transform:scale(1)}}
  `;root.appendChild(s)}
  core.querySelector('.v4-segments')?.remove();
  if(!core.querySelector('.v4-field'))['v4-field','v4-halo','v4-frame','v4-scan','v4-pulse','v4-reactor'].forEach(c=>{const e=document.createElement('div');e.className=c;core.prepend(e)});
  const sync=()=>{const [k,c,soft]=stateMeta(core);core.style.setProperty('--jv-core-state',c);core.style.setProperty('--jv-core-state-soft',soft);core.dataset.v4State=k};sync();if(!core.__v4Observer){const o=new MutationObserver(sync);o.observe(core,{attributes:true,attributeFilter:['class']});core.__v4Observer=o}if(!core.dataset.v4BootPlayed){core.dataset.v4BootPlayed='1';core.classList.add('v4-boot');setTimeout(()=>{core.classList.remove('v4-boot');sync()},2600)}
 };
 const wrap=(name,after)=>{const base=Panel.prototype[name];if(!base)return;Panel.prototype[name]=function(...a){const out=base.apply(this,a);if(out&&typeof out.then==='function')return out.then(v=>{after.call(this);return v});after.call(this);return out}};
 wrap('_render',function(){this._v4InstallShell()});
 wrap('_bootCore',function(){this._v4InstallShell();this._v4InstallCore();this._v4LoadSecurityEntities()});
 const baseToggle=Panel.prototype._toggle;if(baseToggle)Panel.prototype._toggle=function(id){const out=baseToggle.call(this,id);if(id==='settingsPanel'&&this.shadowRoot?.getElementById(id)?.classList.contains('open'))this._v4LoadSecurityEntities();return out};
 Panel.prototype.__jarvisV4UiInstalled=true;
}
